server:
  port: 8000

spring:
  application:
    name: cloud-docker-service

eureka:
  client:
    # 表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true
    fetch-registry: true
    service-url:
      # 单机版
      # defaultZone: http://localhost:7001/eureka
      # 集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 集群版
  instance:
    instance-id: cloud-docker-service80
    prefer-ip-address: true
    # 心跳检测也续约时间
    # 开发时设置小些，保证服务关闭后注册中心能及时剔除服务
    # Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认30秒）
    lease-renewal-interval-in-seconds: 1
    # Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认是90秒），超时将剔除服务
    lease-expiration-duration-in-seconds: 2


docker:
  # host: "tcp://192.168.1.80:2375"
  # ipAddress: "192.168.1.80"
  # host: "tcp://81.70.240.72:2375"
  # ipAddress: "81.70.240.72"
#  host: "tcp://127.0.0.1:2375"
#  ipAddress: "127.0.0.1"
  host: "tcp://49.232.78.91:2375"
  ipAddress: "49.232.78.91"