server:
  port: 8080

spring:
  application:
    name: attack-detection-dockerkubernetesdemo
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/attackdetection?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: s002611

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.edu.pku.entities