server:
  port: 9000

spring:
  application:
    name: cloud-sandbox-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/attack_detection?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: s002611
  rabbitmq:
    #host: 172.16.17.10
    host: 192.168.1.10
    port: 5672
    username: ems
    password: 123
    virtual-host: /ems
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.edu.pku.entities

#eureka:
#  client:
#    register-with-eureka: false
#    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

# 设置Feign客户端超时时间（OpenFeign默认支持ribbon）
ribbon:
  # 指的是建立连接所用的时间，适用于网络状况正常的情况下，两端链接所用的时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

host:
  serviceAddress: "http://127.0.0.1:"